### ISSUE TITLE
Anaconda installation issues on Windows

### ISSUE THREAD

**Issue by Jezzffihuter** [HKUST-SOSC4300-5500/Tutorial-Material#5]
Hi, I am a Windows 10 user, and I have some issues on Anaconda installation as below.
![image](https://user-images.githubusercontent.com/65488456/93557988-08c5df80-f9af-11ea-825a-f3c5327f9c93.png)
However, I think that I have installed Anaconda and have set up the environmental variable.
![image](https://user-images.githubusercontent.com/65488456/93558081-3dd23200-f9af-11ea-8e31-139c9a43e7ae.png)
![image](https://user-images.githubusercontent.com/65488456/93558099-488cc700-f9af-11ea-82e4-09bf5f289cac.png)
Please kindly inform me of its solution, thanks.

**Comment by philohistoria** [comment]
That's a little bit weird. Based on my eyeballing your setting of path variables looks correct. Are you sure your anaconda is installed on \Anacoonda\Anaconda installed\

You can come to my office hour or Wenwei'office hour if you still have trouble.
